st = "Riaan" 

print(st*5)
print(st[1:4])
print(st.upper())
print(st.lower())
print(st.replace("Riaan", "Ria"))
print(st.find("a"))
print(len(st))
print(st.startswith("Ri"))
print(st.endswith("an"))
print(st.isalpha())
print(st.isdigit())
print(st.split("i"))
print(st.count("a"))
print(st.index("a"))
print(st.capitalize())
print(st.title())
print(st.swapcase())
print(st.center(20, "-"))
print(st.ljust(20, "*"))
print(st.rjust(20, "+"))
print(st.strip("R"))
print(st.partition("a"))
print(st.rpartition("a"))
print(st.zfill(10))
print(st.encode("utf-8"))
print(st.format())