str1 = "Hello"
str2 = "World"
print("str1 + str2", str1 + str2)
print("str1 * 3:", str1 * 3)
print("str1[1]:", str1[1])
print("str2[0:3]:", str2[0:3])
print("len(str1):", len(str1))
print("str1.lower():", str1.lower())
print("str2.upper():", str2.upper())
print("str1.replace('H', 'h'):", str1.replace('H', 'h'))
print("str1.split('e'):", str1.split('e'))
print("str1.find('l'):", str1.find('l'))
print("str1.count('l'):", str1.count('l'))
print("str1.startswith('He'):", str1.startswith('He'))
print("str2.endswith('ld'):", str2.endswith('ld'))
print("str1.isalpha():", str1.isalpha())
print("str1.isdigit():", str1.isdigit())
print("str1.strip():", str1.strip())
print("str1.capitalize():", str1.capitalize())
print("str1.title():", str1.title())
print("str1.center(20):", str1.center(20))
print("str1.zfill(10):", str1.zfill(10))
print("str1.index('e'):", str1.index('e'))
print("str1.swapcase():", str1.swapcase())
print("str1.format():", "{} {}".format(str1, str2))