name = str(input("Enter your name: "))
age = int(input("Enter your age: "))
weight = float(input("Enter your weight: "))
is_student = bool(input("Are you a student (True/False): "))
print("Name:", name, "Datatype:", type(name))
print("Age:", age, "Datatype:", type(age))
print("Weight:", weight, "Datatype:", type(weight))
print("Is Student:", is_student, "Datatype:", type(is_student))
weight = int (weight)
age = float (age)
print("After conversion:")
print("Weight:", weight, "Datatype:", type(weight))
print("Age:", age, "Datatype:", type(age))
